version: '3'
services:
  proxy:
    build: 
      context: ./
      dockerfile: ./proxy/Dockerfile
    ports:
      - "80:80"
    environment:
      BACKEND: api
    volumes:
      - ./src/client/dist/:/usr/share/nginx/html/
    depends_on:
      - api
    restart: always
  api:
    build: 
      context: ./
      dockerfile: ./api/Dockerfile
    env_file: ./api/.api_env
    command: 'python src/server.py'
    volumes:
      - ./src:/usr/src/api/src
    restart: always