version: '3'
services:
  proxy:
    image: tetsis/cloud-voice-recognition-proxy
    ports:
      - "80:80"
    environment:
      BACKEND: api
    volumes:
      - ./proxy/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - api
    restart: always
  api:
    image: tetsis/cloud-voice-recognition-api
    env_file: ./api/.api_env
    command: 'python src/server.py'
    volumes:
      - ./api/GOOGLE_APPLICATION_CREDENTIALS.json:/usr/src/api/credentials/GOOGLE_APPLICATION_CREDENTIALS.json
    restart: always