version: '3'
services:
  proxy:
    image: 961422418814.dkr.ecr.ap-northeast-1.amazonaws.com/cvr-proxy
    ports:
      - "80:80"
    environment:
      BACKEND: api
      - ./src/client/dist/:/usr/share/nginx/html/
    depends_on:
      - api
    restart: always
  api:
    image: 961422418814.dkr.ecr.ap-northeast-1.amazonaws.com/cvr-api
    env_file: ./api/.api_env
    command: 'python src/server.py'
    restart: always